export const UserActionTypes = {
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  CREATE_USER_EMAIL_START: "CREATE_USER_EMAIL_START",
  CREATE_USER_EMAIL_SUCCESS: "CREATE_USER_EMAIL_SUCCESS",
  CREATE_USER_EMAIL_FAILURE: "CREATE_USER_EMAIL_FAILURE"
};
